M48
; DRILL file KiCad 10.0.0 date 2026-05-31T15:44:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-31T15:44:40-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X157.5Y-53.0
X157.5Y-55.54
T2
X103.5Y-47.5
X161.5Y-47.5
M30
